"""
Connector code templates.
Each template follows the same basic interface:
    connect(), test_connection(), fetch_schema(), close()
This keeps every generated connector standardized and reusable.
"""

TEMPLATE_VERSIONS = {
    "postgresql": "1.1",
    "mysql": "1.1",
    "sqlserver": "1.1",
    "rest_api": "1.1",
}

TEMPLATE_CHANGELOG = {
    "postgresql": [
        {"version": "1.0", "notes": "Initial standardized connector: connect(), test_connection(), fetch_schema(), close()."},
        {"version": "1.1", "notes": "Added disconnect(), context manager support (__enter__/__exit__), and memory-safe extract_batch()."},
    ],
    "mysql": [
        {"version": "1.0", "notes": "Initial standardized connector: connect(), test_connection(), fetch_schema(), close()."},
        {"version": "1.1", "notes": "Added disconnect(), context manager support (__enter__/__exit__), and memory-safe extract_batch()."},
    ],
    "sqlserver": [
        {"version": "1.0", "notes": "Initial standardized connector: connect(), test_connection(), fetch_schema(), close()."},
        {"version": "1.1", "notes": "Added disconnect(), context manager support (__enter__/__exit__), and memory-safe extract_batch()."},
    ],
    "rest_api": [
        {"version": "1.0", "notes": "Initial standardized connector: connect(), test_connection(), fetch_schema(), close()."},
        {"version": "1.1", "notes": "Added disconnect(), context manager support (__enter__/__exit__), and paginated extract_batch()."},
    ],
}


def get_template_version(source_type):
    return TEMPLATE_VERSIONS.get(source_type, "unknown")


def get_template_changelog(source_type):
    return TEMPLATE_CHANGELOG.get(source_type, [])

POSTGRESQL_TEMPLATE = '''"""
Auto-generated PostgreSQL Connector
Template version: {template_version}
Generated by: Data Source Onboarding Agent
"""
import psycopg2
from psycopg2 import OperationalError


class {class_name}:
    """Reusable connector for the '{source_name}' PostgreSQL database."""

    def __init__(self, host, port, database, user, password):
        self.host = host
        self.port = port
        self.database = database
        self.user = user
        self.password = password
        self.connection = None

    def connect(self):
        try:
            self.connection = psycopg2.connect(
                host=self.host,
                port=self.port,
                dbname=self.database,
                user=self.user,
                password=self.password,
            )
            return True
        except OperationalError as e:
            print(f"Connection failed: {{e}}")
            return False

    def test_connection(self):
        ok = self.connect()
        if ok:
            self.close()
        return ok

    def fetch_schema(self):
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema='public';"
        )
        tables = [row[0] for row in cursor.fetchall()]
        cursor.close()
        return tables

    def close(self):
        if self.connection:
            self.connection.close()
            self.connection = None

    def disconnect(self):
        """Alias for close(), matching common connector interface naming."""
        self.close()

    def extract_batch(self, query, batch_size=500):
        """Memory-safe batch extraction — yields rows in chunks instead of
        loading the whole result set into memory at once."""
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute(query)
        while True:
            rows = cursor.fetchmany(batch_size)
            if not rows:
                break
            yield rows
        cursor.close()

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


if __name__ == "__main__":
    connector = {class_name}(
        host="{host}",
        port={port},
        database="{database}",
        user="{user}",
        password="YOUR_PASSWORD_HERE",
    )
    print("Connected:", connector.test_connection())
'''

MYSQL_TEMPLATE = '''"""
Auto-generated MySQL Connector
Template version: {template_version}
Generated by: Data Source Onboarding Agent
"""
import mysql.connector
from mysql.connector import Error


class {class_name}:
    """Reusable connector for the '{source_name}' MySQL database."""

    def __init__(self, host, port, database, user, password):
        self.host = host
        self.port = port
        self.database = database
        self.user = user
        self.password = password
        self.connection = None

    def connect(self):
        try:
            self.connection = mysql.connector.connect(
                host=self.host,
                port=self.port,
                database=self.database,
                user=self.user,
                password=self.password,
            )
            return True
        except Error as e:
            print(f"Connection failed: {{e}}")
            return False

    def test_connection(self):
        ok = self.connect()
        if ok:
            self.close()
        return ok

    def fetch_schema(self):
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute("SHOW TABLES;")
        tables = [row[0] for row in cursor.fetchall()]
        cursor.close()
        return tables

    def close(self):
        if self.connection and self.connection.is_connected():
            self.connection.close()
            self.connection = None

    def disconnect(self):
        self.close()

    def extract_batch(self, query, batch_size=500):
        """Memory-safe batch extraction — yields rows in chunks."""
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute(query)
        while True:
            rows = cursor.fetchmany(batch_size)
            if not rows:
                break
            yield rows
        cursor.close()

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


if __name__ == "__main__":
    connector = {class_name}(
        host="{host}",
        port={port},
        database="{database}",
        user="{user}",
        password="YOUR_PASSWORD_HERE",
    )
    print("Connected:", connector.test_connection())
'''

SQLSERVER_TEMPLATE = '''"""
Auto-generated SQL Server Connector
Template version: {template_version}
Generated by: Data Source Onboarding Agent
"""
import pyodbc


class {class_name}:
    """Reusable connector for the '{source_name}' SQL Server database."""

    def __init__(self, host, port, database, user, password):
        self.host = host
        self.port = port
        self.database = database
        self.user = user
        self.password = password
        self.connection = None

    def connect(self):
        try:
            conn_str = (
                f"DRIVER={{{{ODBC Driver 17 for SQL Server}}}};"
                f"SERVER={{self.host}},{{self.port}};"
                f"DATABASE={{self.database}};"
                f"UID={{self.user}};PWD={{self.password}}"
            )
            self.connection = pyodbc.connect(conn_str)
            return True
        except pyodbc.Error as e:
            print(f"Connection failed: {{e}}")
            return False

    def test_connection(self):
        ok = self.connect()
        if ok:
            self.close()
        return ok

    def fetch_schema(self):
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;")
        tables = [row[0] for row in cursor.fetchall()]
        cursor.close()
        return tables

    def close(self):
        if self.connection:
            self.connection.close()
            self.connection = None

    def disconnect(self):
        self.close()

    def extract_batch(self, query, batch_size=500):
        """Memory-safe batch extraction — yields rows in chunks."""
        if not self.connection:
            self.connect()
        cursor = self.connection.cursor()
        cursor.execute(query)
        while True:
            rows = cursor.fetchmany(batch_size)
            if not rows:
                break
            yield rows
        cursor.close()

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


if __name__ == "__main__":
    connector = {class_name}(
        host="{host}",
        port={port},
        database="{database}",
        user="{user}",
        password="YOUR_PASSWORD_HERE",
    )
    print("Connected:", connector.test_connection())
'''

REST_API_TEMPLATE = '''"""
Auto-generated REST API Connector
Template version: {template_version}
Generated by: Data Source Onboarding Agent
"""
import requests


class {class_name}:
    """Reusable connector for the '{source_name}' REST API."""

    def __init__(self, base_url, api_key=None):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.session = requests.Session()
        if self.api_key:
            self.session.headers.update({{"Authorization": f"Bearer {{self.api_key}}"}})

    def connect(self):
        return self.test_connection()

    def test_connection(self):
        try:
            response = self.session.get(self.base_url, timeout=5)
            return response.status_code < 500
        except requests.RequestException as e:
            print(f"Connection failed: {{e}}")
            return False

    def fetch_schema(self, endpoint=""):
        """Fetch a sample response from an endpoint to inspect its shape."""
        url = f"{{self.base_url}}/{{endpoint}}".rstrip("/")
        response = self.session.get(url, timeout=5)
        response.raise_for_status()
        return response.json()

    def close(self):
        self.session.close()

    def disconnect(self):
        self.close()

    def extract_batch(self, endpoint="", params=None, batch_size=100):
        """Memory-safe batch extraction via simple page/limit pagination.
        Adjust the pagination params to match your actual API's convention."""
        params = dict(params or {{}})
        page = 1
        while True:
            params.update({{"page": page, "limit": batch_size}})
            url = f"{{self.base_url}}/{{endpoint}}".rstrip("/")
            response = self.session.get(url, params=params, timeout=10)
            response.raise_for_status()
            data = response.json()
            if not data:
                break
            yield data
            page += 1

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


if __name__ == "__main__":
    connector = {class_name}(
        base_url="{host}",
        api_key="YOUR_API_KEY_HERE",
    )
    print("Connected:", connector.test_connection())
'''

TEMPLATES = {
    "postgresql": POSTGRESQL_TEMPLATE,
    "mysql": MYSQL_TEMPLATE,
    "sqlserver": SQLSERVER_TEMPLATE,
    "rest_api": REST_API_TEMPLATE,
}